window.PRICING_CONTROL_TOWER_DATA = {
  meta: {
    mode: "demo",
    snapshotDate: "2026-08-01",
    currency: "PEN",
    scope: "9 proyectos · unidades residenciales",
    sourceLabel: "Dataset demostrativo incluido en el repositorio",
    disclaimer: "Los proyectos están anonimizados y las cifras son demostrativas; no deben usarse para decisiones comerciales."
  },
  projects: [
    {
      id: "project-a",
      name: "Proyecto A",
      phase: "En venta",
      availableUnits: 18,
      availableValue: 8900000,
      priceM2: 6100,
      marketGapPct: 0.02,
      netSales30d: 2.2,
      targetSales30d: 2.5,
      conversionPct: 7.8,
      targetConversionPct: 8.0,
      avgDaysStock: 96,
      cancellations30d: 1,
      leads30d: 74,
      separations30d: 6
    },
    {
      id: "project-b",
      name: "Proyecto B",
      phase: "En venta",
      availableUnits: 27,
      availableValue: 12800000,
      priceM2: 5800,
      marketGapPct: 0.05,
      netSales30d: 1.4,
      targetSales30d: 2.4,
      conversionPct: 4.9,
      targetConversionPct: 7.5,
      avgDaysStock: 148,
      cancellations30d: 1,
      leads30d: 82,
      separations30d: 4
    },
    {
      id: "project-c",
      name: "Proyecto C",
      phase: "En venta",
      availableUnits: 13,
      availableValue: 7100000,
      priceM2: 6500,
      marketGapPct: -0.02,
      netSales30d: 3.1,
      targetSales30d: 2.4,
      conversionPct: 9.8,
      targetConversionPct: 8.0,
      avgDaysStock: 64,
      cancellations30d: 0,
      leads30d: 61,
      separations30d: 6
    },
    {
      id: "project-d",
      name: "Proyecto D",
      phase: "En venta",
      availableUnits: 34,
      availableValue: 18400000,
      priceM2: 6200,
      marketGapPct: 0.07,
      netSales30d: 1.8,
      targetSales30d: 2.8,
      conversionPct: 5.6,
      targetConversionPct: 8.0,
      avgDaysStock: 172,
      cancellations30d: 1,
      leads30d: 89,
      separations30d: 5
    },
    {
      id: "project-e",
      name: "Proyecto E",
      phase: "En venta",
      availableUnits: 21,
      availableValue: 10600000,
      priceM2: 5900,
      marketGapPct: 0.01,
      netSales30d: 2.9,
      targetSales30d: 2.6,
      conversionPct: 8.3,
      targetConversionPct: 8.0,
      avgDaysStock: 82,
      cancellations30d: 0,
      leads30d: 72,
      separations30d: 6
    },
    {
      id: "project-f",
      name: "Proyecto F",
      phase: "Últimas unidades",
      availableUnits: 9,
      availableValue: 5800000,
      priceM2: 7100,
      marketGapPct: -0.04,
      netSales30d: 3.4,
      targetSales30d: 2.5,
      conversionPct: 11.1,
      targetConversionPct: 8.5,
      avgDaysStock: 45,
      cancellations30d: 0,
      leads30d: 54,
      separations30d: 6
    },
    {
      id: "project-g",
      name: "Proyecto G",
      phase: "En venta",
      availableUnits: 16,
      availableValue: 8100000,
      priceM2: 6000,
      marketGapPct: 0.03,
      netSales30d: 2.0,
      targetSales30d: 2.3,
      conversionPct: 6.2,
      targetConversionPct: 7.5,
      avgDaysStock: 105,
      cancellations30d: 1,
      leads30d: 80,
      separations30d: 5
    },
    {
      id: "project-h",
      name: "Proyecto H",
      phase: "En venta",
      availableUnits: 29,
      availableValue: 14200000,
      priceM2: 5700,
      marketGapPct: 0.08,
      netSales30d: 1.2,
      targetSales30d: 2.5,
      conversionPct: 4.5,
      targetConversionPct: 7.5,
      avgDaysStock: 190,
      cancellations30d: 2,
      leads30d: 88,
      separations30d: 4
    },
    {
      id: "project-i",
      name: "Proyecto I",
      phase: "En venta",
      availableUnits: 42,
      availableValue: 22500000,
      priceM2: 6400,
      marketGapPct: 0.06,
      netSales30d: 1.7,
      targetSales30d: 3.0,
      conversionPct: 5.1,
      targetConversionPct: 8.0,
      avgDaysStock: 160,
      cancellations30d: 1,
      leads30d: 98,
      separations30d: 5
    }
  ]
};
